# Generated by Django 5.0 on 2025-11-26 23:37

from django.db import migrations, models


def resume_upload_path(instance, filename):
    return f"resumes/{filename}"


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemarkdown',
            name='file',
            field=models.FileField(blank=True, help_text='Upload your resume in Markdown (.md) format. Maximum 10,000 words.', upload_to=resume_upload_path),
        ),
    ]
