# Generated by Django 5.0 on 2025-11-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_remove_resume_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatlog',
            name='session_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
