# Generated by Django 5.0 on 2025-11-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, help_text='Certificate year', max_length=50)),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'resume_certificate',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('type', models.CharField(help_text='Contact type: phone, email, github, telegram, hh, etc.', max_length=50)),
                ('label', models.CharField(help_text='Contact label (Phone, Email, GitHub, etc.)', max_length=100)),
                ('value', models.CharField(help_text='Contact value', max_length=200)),
                ('href', models.URLField(help_text='Contact link')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'resume_contact_info',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, help_text='Location (e.g., CA, USA)', max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('faculty', models.CharField(blank=True, help_text='Faculty or major', max_length=200)),
                ('year', models.CharField(max_length=50)),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'db_table': 'resume_education',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.CharField(help_text='E.g.: Aug 2024', max_length=50)),
                ('end_date', models.CharField(help_text='E.g.: Present or Aug 2024', max_length=50)),
                ('description', models.TextField()),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'db_table': 'resume_experience',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=0, help_text='Proficiency percentage (0-100)')),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'resume_language',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, help_text='What this setting does')),
            ],
            options={
                'db_table': 'setting',
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('category_name_key', models.CharField(help_text='Key for category translation', max_length=100)),
                ('category_color', models.CharField(default='from-blue-500 to-cyan-500', help_text='CSS classes for gradient', max_length=100)),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'resume_skill',
                'ordering': ['category_name_key', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique project code (e.g.: ai-text-tools, simple-alarm)', max_length=100)),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Project description')),
                ('technologies', models.JSONField(default=list, help_text='List of technologies')),
                ('link', models.URLField(blank=True, default='#')),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'resume_project',
                'ordering': ['order'],
                'unique_together': {('code', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('firstname', models.CharField(help_text='First name', max_length=100)),
                ('lastname', models.CharField(help_text='Last name', max_length=100)),
                ('resume_title', models.CharField(help_text='Title for hero section', max_length=200)),
                ('resume_description', models.TextField(help_text='Short description for hero section')),
                ('about_me', models.TextField(help_text='Full description for About section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': 'resume',
                'unique_together': {('language',)},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Translation key (e.g., 'certificates', 'education')", max_length=100)),
                ('language', models.CharField(db_index=True, help_text="Language code (e.g., 'en', 'ru', 'zh')", max_length=10)),
                ('value', models.CharField(help_text='Translated text', max_length=255)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['key', 'language'],
                'indexes': [models.Index(fields=['key', 'language'], name='resume_tran_key_ab6d81_idx')],
                'unique_together': {('key', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referer', models.URLField(blank=True, max_length=500, null=True)),
                ('page', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('first_visit', models.DateTimeField(auto_now_add=True, db_index=True, help_text='First visit timestamp')),
                ('last_visit', models.DateTimeField(auto_now=True, help_text='Last visit timestamp (updated on each request)')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': 'visit',
                'ordering': ['-last_visit'],
                'indexes': [models.Index(fields=['-last_visit'], name='visit_last_vi_0fa700_idx'), models.Index(fields=['session_id'], name='visit_session_f3960a_idx'), models.Index(fields=['ip_address'], name='visit_ip_addr_2c819a_idx'), models.Index(fields=['page'], name='visit_page_741fff_idx')],
            },
        ),
    ]
