# Generated by Django 5.0 on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', help_text='Type: photo or video', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of the item')),
                ('photo_data', models.BinaryField(blank=True, help_text='Photo stored as binary data', null=True)),
                ('photo_mime_type', models.CharField(blank=True, help_text='MIME type of the photo (e.g., image/jpeg)', max_length=50, null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL for video (e.g., YouTube link)')),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Item',
                'verbose_name_plural': 'Carousel Items',
                'db_table': 'resume_carousel',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description of the document')),
                ('photo_data', models.BinaryField(help_text='Document image stored as binary data')),
                ('photo_mime_type', models.CharField(default='image/jpeg', help_text='MIME type of the image', max_length=50)),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'resume_document',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price amount', max_digits=10)),
                ('currency', models.CharField(default='RUB', help_text='Currency code (e.g., RUB, USD, EUR)', max_length=10)),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'resume_price',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5, help_text='Rating from 1 to 5 stars')),
                ('text', models.TextField(help_text='Review text')),
                ('author', models.CharField(blank=True, help_text='Author name (optional)', max_length=100)),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, ru, zh)', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'resume_review',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
