# Generated by Django 5.0 on 2026-01-03 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_carousel_document_price_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date created (editable)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date created (editable)'),
        ),
    ]
