# Generated by Django 5.0 on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_carousel_created_at_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='patronymic',
            field=models.CharField(blank=True, default='', help_text='Patronymic/Middle name (for Russian)', max_length=100),
        ),
    ]
